openapi: 3.0.0

paths:
  # ED-01 : ELECTION OFFICIALS ------------------------------------------------------------------------

  # ED-02 : PARTICIPANTS ------------------------------------------------------------------------------

  # ED-03 : ELECTION RESULTS --------------------------------------------------------------------------
  /results:
    put:
      summary: This endpoint calculate the results
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:putCalculateResults/invocations"
        httpMethod: "POST"
  
  /results/nationwide:
    get:
      summary:  This endpoint returns the results by nationwide
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:getNationwideResults/invocations"
        httpMethod: "POST"
  
  /results/cities/{citie_id}:
    get:
      summary:  This endpoint returns the results by city
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:getCityResults/invocations"
        httpMethod: "POST"  
        
  /results/schools/{school_id}:
    get:
      summary: This endpoint returns the results by school
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:getSchoolResults/invocations"
        httpMethod: "POST"
        
  /persons/{person_id}/verify:
    get:
      summary: This endpoint returns the place where the client vote 
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:getPersonPlace/invocations"
        httpMethod: "POST"
          
# ED-04 : INVALIDATIONS -----------------------------------------------------------------------------
  /cities/{city_id}/schools/{school_id}/booths/{booth_id}/invalidate:
    put:
      summary: This endpoint saves an invalid booth into de database
      parameters:
        - name: city_id
          in: path
          required: true
          description: City unique Id
        - name: school_id
          in: path
          required: true
          description: School unique Id
        - name: booth_id
          in: path
          required: true
          description: Booth unique Id
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:invalidateBooth/invocations"
        httpMethod: "POST"
        
  /invalids:
    get:
      summary: This endpoint returns all the invalid booths across the country
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:showInvalidBooths/invocations"
        httpMethod: "POST"
        
  /invalids/cities:
    get:
      summary: This endpoint returns all the invalid booths across the country by city
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:showInvalidBoothsByCity/invocations"
        httpMethod: "POST"
        
  /invalids/cities/{city_id}/schools:
    get:
      summary: This endpoint returns all the invalid booths by school across a given city
      parameters:
        - name: city_id
          in: path
          required: true
          description: City unique Id
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:showInvalidBoothsBySchool/invocations"
        httpMethod: "POST"