AWSTemplateFormatVersion : '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31

Description: Election Day project
Resources:
# ED-01 : ELECTION OFFICIALS ------------------------------------------------------------------------

# ED-02 : PARTICIPANTS ------------------------------------------------------------------------------

  RegisterParticipant:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: registerparticipant
      Handler: Participants.registerparticipant
      Runtime: python3.6
      CodeUri: package/
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref ElectionDayTable
        - DynamoDBReadPolicy:
            TableName: !Ref ElectionDayTable
      Environment:
        Variables:
          ELECTIONDAY_TABLE: !Ref ElectionDayTable 
      Events:
        Invalidate:
          Type: Api
          Properties:
            RestApiId: !Ref ElectionDayAPI
            Path: "/persons/{person_id}/register"
            Method: PUT

# ED-03 : ELECTION RESULTS --------------------------------------------------------------------------

# ED-04 : INVALIDATIONS -----------------------------------------------------------------------------

  InvalidateBooth:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: invalidateBooth
      Handler: Invalidations.invalidateBooth
      Runtime: python3.6
      CodeUri: package/
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref ElectionDayTable
        - DynamoDBReadPolicy:
            TableName: !Ref ElectionDayTable
      Environment:
        Variables:
          ELECTIONDAY_TABLE: !Ref ElectionDayTable 
      Events:
        Invalidate:
          Type: Api
          Properties:
            RestApiId: !Ref ElectionDayAPI
            Path: "/booths/{booth_id}/invalidate"
            Method: PUT

  ShowInvalidBooths:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: showInvalidBooths
      Handler: Invalidations.showInvalidBooths
      Runtime: python3.6
      CodeUri: package/
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ElectionDayTable
      Environment:
        Variables:
          ELECTIONDAY_TABLE: !Ref ElectionDayTable 
      Events:
        GetUsers:
          Type: Api
          Properties:
            RestApiId: !Ref ElectionDayAPI
            Path: "/invalids"
            Method: GET
            
  ShowInvalidBoothsByCity:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: showInvalidBoothsByCity
      Handler: Invalidations.showInvalidBoothsByCity
      Runtime: python3.6
      CodeUri: package/
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ElectionDayTable
      Environment:
        Variables:
          ELECTIONDAY_TABLE: !Ref ElectionDayTable 
      Events:
        GetUsers:
          Type: Api
          Properties:
            RestApiId: !Ref ElectionDayAPI
            Path: "/invalids/cities"
            Method: GET
            
  ShowInvalidBoothsBySchool:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: showInvalidBoothsBySchool
      Handler: Invalidations.showInvalidBoothsBySchool
      Runtime: python3.6
      CodeUri: package/
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ElectionDayTable
      Environment:
        Variables:
          ELECTIONDAY_TABLE: !Ref ElectionDayTable 
      Events:
        GetUsers:
          Type: Api
          Properties:
            RestApiId: !Ref ElectionDayAPI
            Path: "/invalids/cities/{city_id}/schools"
            Method: GET

# TABLE ---------------------------------------------------------------------------------------------
  ElectionDayTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: election-day-table
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
            
# API Gateway ---------------------------------------------------------------------------------------
  ElectionDayAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: election-day-api
      StageName: prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: swagger.yaml