AWSTemplateFormatVersion : '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31

Description: Election Day project
Resources:
# ED-01 : ELECTION OFFICIALS ------------------------------------------------------------------------

# ED-02 : PARTICIPANTS ------------------------------------------------------------------------------

# ED-03 : ELECTION RESULTS --------------------------------------------------------------------------

# ED-04 : INVALIDATIONS -----------------------------------------------------------------------------

# TABLE ---------------------------------------------------------------------------------------------
  ElectionDayTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: election-day-table
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
            
# API Gateway ---------------------------------------------------------------------------------------
  ElectionDayAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: election-day-api
      StageName: prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: swagger.yaml